flux_github_user: "{{ github_username }}"
flux_github_token: "{{ github_token }}"
flux_github_repo: "homelab"
flux_target_branch: "main"
flux_cluster_path: "./kubernetes/homelab"
flux_kubeconfig: "/etc/rancher/k3s/k3s.yaml"