dnsmasq_port: 53
dnsmasq_listen_addresses:
  - 127.0.0.1
  - "{{ ansible_default_ipv4.address }}"

# Upstream public/upstream resolvers
dnsmasq_upstream_servers:
  - 1.1.1.1
  - 8.8.8.8

# Local domain definitions
dnsmasq_domain: "homelab.local"
dnsmasq_expand_hosts: true

# Static A/AAAA and CNAME overrides
dnsmasq_records:
  - { name: "homelab.local", ip: "192.168.1.103" }

# dnsmasq_cnames:
  # - { alias: "files.internal.lab", target: "nas.internal.lab" }