- name: Tasks to run before all else
  hosts: all 
  become: true
  tasks:
    - name: Wait for apt locks to clear and update cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      register: apt_status
      until: apt_status is success
      delay: 30
      retries: 20

- name: Deploy DNS server
  hosts: dns
  become: true
  roles:
    - dnsmasq

- name: Deploy Tailscale
  hosts: tailscale
  become: true
  roles:
    - role: artis3n.tailscale.machine
      vars:
        # Pass via Ansible Vault or environment variable in production
        tailscale_authkey: "{{ tailscale_auth_key }}"
        tailscale_ssh: false
        # Ensure --ssh is removed from extra arguments
        tailscale_args: ""

- name: Install Node-exporter
  hosts: all
  become: true
  roles: 
    - role: prometheus.prometheus.node_exporter

- name: Install Prometheus on RPI-5
  hosts: 
    - monitoring
  become: true
  roles:
    - role: prometheus.prometheus.prometheus
      vars:
        prometheus_targets: 
          node:
            - targets:
                - "192.168.1.99:9100"
                - "192.168.1.101:9100"
                - "192.168.1.102:9100"
                - "192.168.1.103:9100"
                - "192.168.1.104:9100"
                - "192.168.1.105:9100"


- name: Deploy Kubernetes Control plane
  hosts: kube-ctl
  become: true
  roles: 
    - kubernetes-ctl
    - fluxcd

- name: Deploy Kubernetes nodes
  hosts: kube-nodes
  become: true
  roles:
    - kubernetes-nodes