- name: Tasks to run before all else
  hosts: all 
  become: true
  tasks:
    - name: Wait for apt locks to clear and update cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      register: apt_status
      until: apt_status is success
      delay: 30
      retries: 20

- name: Deploy and Configure Grafana
  hosts: monitoring
  become: true
  pre_tasks:
    - name: Install required Python libraries for apt modules
      ansible.builtin.apt:
        name:
          - python3-debian
          - python3-apt
        state: present
        update_cache: true

- name: Deploy DNS server
  hosts: dns
  become: true
  roles:
    - dnsmasq

- name: Deploy Tailscale
  hosts: tailscale
  become: true
  roles:
    - role: artis3n.tailscale.machine
      vars:
        # Pass via Ansible Vault or environment variable in production
        tailscale_authkey: "{{ tailscale_auth_key }}"
        tailscale_ssh: false
        # Ensure --ssh is removed from extra arguments
        tailscale_args: ""

- name: Install Node-exporter
  hosts: all
  become: true
  roles: 
    - role: prometheus.prometheus.node_exporter

- name: Install Prometheus on RPI-5
  hosts: 
    - monitoring
  become: true
  roles:
    - role: prometheus.prometheus.prometheus
      vars:
        prometheus_targets: 
          node:
            - targets:
                - "192.168.1.99:9100"
                - "192.168.1.101:9100"
                - "192.168.1.102:9100"
                - "192.168.1.103:9100"
                - "192.168.1.104:9100"
                - "192.168.1.105:9100"

- name: Install Grafana on RPI-5
  hosts:
    - monitoring
  become: true
  roles: 
    - role: grafana.grafana.grafana
      vars:
        grafana_cap_net_bind_service: true
        grafana_ini:
          security:
            admin_user: admin
            admin_password: "{{ grafana_password }}"
          server:
            http_port: 80
            domain: "grafana.homelab.local"

        grafana_datasources:
          - name: "Prometheus"
            type: "prometheus"
            access: "proxy"
            url: "http://localhost:9090"
            isDefault: true
            jsonData:
              timeInterval: "15s"

        grafana_dashboards:
          - name: "Homelab monitoring"
            grafana_dashboard_id: 1860
            revision: 37
            datasource: "Prometheus"

- name: Deploy Kubernetes Control plane
  hosts: kube-ctl
  become: true
  roles: 
    - kubernetes-ctl
    - fluxcd

- name: Deploy Kubernetes nodes
  hosts: kube-nodes
  become: true
  roles:
    - kubernetes-nodes