name: Deploy via Local Ansible

on:
  push:
    branches:
      - main

jobs:
  tofu:
    runs-on: self-hosted
    environment: R2
    env:
      # Injected via GitHub Repository Secrets for Cloudflare R2
      AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY }}

    steps:
      - name: Sync latest repository code
        run: |
          cd ~/homelab
          git pull origin-ssh main

      - name: Tofu Init
        run: |
          cd ~/homelab/terraform
          tofu init \
            -backend-config="access_key=$AWS_ACCESS_KEY_ID" \
            -backend-config="secret_key=$AWS_SECRET_ACCESS_KEY"

      - name: Tofu Plan
        run: |
          cd ~/homelab/terraform
          tofu plan -no-color

      - name: Tofu Apply
        run: |
          cd ~/homelab/terraform
          tofu apply -auto-approve -no-color

  deploy:
    runs-on: self-hosted
    needs: tofu

    steps:
      - name: Install required collections
        run: |
          cd ~/homelab/ansible
          ansible-galaxy collection install artis3n.tailscale
          ansible-galaxy collection install prometheus.prometheus
          ansible-galaxy collection install grafana.grafana

      - name: Run Ansible Playbook
        run: |
          cd ~/homelab/ansible
          /home/homelab/.local/bin/ansible-playbook \
            -i inventory.yaml \
            playbook.yaml \
            --vault-password-file ~/.vault_pass