name: Deploy via Local Ansible

on:
  push:
    branches:
      - main

jobs:
  tofu:
    runs-on: self-hosted

    steps:
      - name: Tofu init
        run: |
          cd ~/homelab/terraform
          tofu init

      - name: Tofu plan
        run: |
          cd ~/homelab/terraform
          tofu plan

      - name: Tofu apply
        run: |
          cd ~/homelab/terraform
          tofu apply

  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest repo files
        run: |
          cd ~/homelab
          git pull origin-ssh main

      - name: Run Playbook
        run: |
          cd ~/homelab/ansible
          /home/homelab/.local/bin/ansible-playbook -i inventory.yaml playbook.yaml